#!/bin/bash
echo "default script initiated"
update-alternatives --install /usr/bin/pager pager /usr/bin/most 999
echo "changing localtime to US/Central with bad hack"
rm /etc/localtime && ln -s /usr/share/zoneinfo/US/Central /etc/localtime
update-alternatives --install /usr/bin/editor editor /usr/bin/xemacs21 999

openssl dsaparam -out /etc/ssl/private/dsaparam.pem 2048
openssl gendsa -rand /var/lib/dpkg/available  -out /etc/ssl/private/secretkey.pem /etc/ssl/private/dsaparam.pem 
openssl req -new -x509 -key /etc/ssl/private/secretkey.pem -out /etc/ssl/cacert.crt
chmod 0600 /etc/ssl/private/dsaparam.pem
chmod 0600 /etc/ssl/private/secretkey.pem
chmod 0644 /etc/ssl/cacert.crt

#default home subdirs
mkdir /etc/skel/bin
mkdir /etc/skel/tmp

