#!/bin/bash
filespath=/root/paella/files/sshd_test
adminuser=`cat $filespath/adminuser`
admingroups="audio video src staff adm operator"
echo "adding", $adminuser
adduser --disabled-password --gecos "Admin User" $adminuser
for grp in $admingroups
do
    adduser $adminuser $grp
done
. /etc/adduser.conf
mkdir -p $DHOME/.ssh
cp $filespath/id_dsa $DHOME/.ssh
cp $filespath/id_dsa.pub $DHOME/.ssh
cp $filespath/authorized_keys $DHOME/.ssh
chown $adminuser:staff -R $DHOME/.ssh
