#!/bin/sh
# /etc/acpi/poweroff.sh
# Initiates a shutdown when the power putton has been
# pressed.

ACPID_AMI_SLEEPING=/var/run/acpid.sleeping
# check, if we just have to wake up
if [ -f "$ACPID_AMI_SLEEPING" ]; then
	rm -f "$ACPID_AMI_SLEEPING"
	/etc/init.d/hwclockfirst.sh start
	exit 0
fi

#otherwise

if ps -Af | grep -q '[k]desktop' && test -f /usr/bin/dcop
then
    dcop --all-users ksmserver ksmserver logout 0 2 0 && exit 0
fi

/sbin/init 0
