#!/usr/bin/env python
import sys
from qt import SIGNAL, SLOT

from kdecore import KCmdLineArgs

from useless.kdebase.error import excepthook

from paella.kde.base.about import AboutData
from paella.kde.main import PaellaMainApplication

# these imports will stay like this until the kdenew is ready to be tested
from paella.kde.main import PaellaMainWindow
from paella.kde.main import PaellaMainWindowSmall

if __name__ == '__main__':
    aboutData = AboutData()
    KCmdLineArgs.init(sys.argv, aboutData)

    # setup error handling
    sys.excepthook = excepthook
    # setup application instance
    app = PaellaMainApplication()
    app.connect(app, SIGNAL('lastWindowClosed()'), app.quit)

    # register with dcop
    dcop = app.dcopClient()
    appid = dcop.registerAs('paella')

    # create main window
    manager_type = app.cfg.get('management_gui', 'manager_type')
    print 'using manager type', manager_type
    # determine which type of windows will be used
    if manager_type == 'listbox_select':
        win = PaellaMainWindowSmall()
    else:
        # default to regular window if bad option value
        win = PaellaMainWindow()

    win.show()

    # set main window in application
    app.setMainWidget(win)

    # start application loop
    #import profile
    #profile.run('app.exec_loop()')
    app.exec_loop()
    
