#!/usr/bin/env python
import os, sys
from optparse import OptionParser

from useless.base import Error, debug
from useless.base.util import makepaths

from paella.base import PaellaConfig
from paella.db.base import get_suite

from paella.installer.base import InstallerConnection

from paella.installer.chroot import ChrootInstaller

parser = OptionParser()

parser.usage = '%prog [options] profile target'
parser.add_option('--logfile', action='store', type='string', dest='logfile',
                  default='/tmp/paella-chroot-installer.log')

opts, args = parser.parse_args(sys.argv[1:])

if os.getuid():
    raise Error, 'need to be root'

cfg = PaellaConfig()
conn = InstallerConnection(cfg)

profile = args[0]
target = args[1]

target = os.path.abspath(target)

installer = ChrootInstaller(conn)
installer.set_logfile(opts.logfile)
installer.set_target(target)
installer.set_profile(profile)
print "installing %s to %s" % (profile, target)
installer.run_all_processes()




sys.stdout.write('all done.\n')


