#!/usr/bin/env python
import os, sys
#from xml.dom.minidom import parse

#from useless.base import Error

from paella.db import PaellaConnection
from paella.db.family import Family
#from paella.db.profile.xmlgen import PaellaProfiles
#from paella.db.profile.xmlparse import ProfileParser


conn = PaellaConnection()
args = sys.argv[1:]
family  = args[0]


fam = Family(conn)
#fam.import_family_xml(path)
fam.write_family(family, '.')
