#!/usr/bin/env python
import os, sys
from os.path import join
from optparse import OptionParser

from useless.base import Error, debug
from useless.db.midlevel import StatementCursor
from useless.sqlgen.clause import Eq

from paella.db import PaellaConnection
from paella.installer.cfdisk import DiskManager

parser = OptionParser()
opts, args = parser.parse_args(sys.argv[1:])

diskname = args[0]
devices = args[1:]

conn = PaellaConnection()

dm = DiskManager(conn)


for device in devices:
    dm.submit_partitions(diskname, device)
    
        
