#!/usr/bin/env python
import sys

from paella.base import PaellaConfig
from paella.installer.nfsbootcd import make_image
    
if __name__ == '__main__':
    cfg = PaellaConfig()
    kernel = sys.argv[1]
    make_image(kernel=kernel)
