#!/bin/bash
# the home directory should be the root of the debian mirror
cd

# make trash directory
if ! [ -d trash ] ; then
    mkdir trash
fi

# make backup directory
if ! [ -d backup ] ; then
    mkdir backup
fi

# run the update
paella-update-debrepos -q

# backup the repository in backup
paella-backup-debrepos

# trash the old dists and pool
mv dists pool trash

# move the backups into place
mv backup/dists backup/pool .

# remove the trash
rm trash -fr
