#!/usr/bin/env python
import os, sys

from useless.base import Error, debug

from paella.profile.base import PaellaConfig
from paella.installer.base import InstallerConnection
from paella.installer.nfsinstaller import NewInstaller

if os.getuid():
    raise Error, 'need to be root'

cfg = PaellaConfig()
conn = InstallerConnection(cfg)
installer = NewInstaller(conn, cfg)

command = sys.argv[1]
if command == 'install':
    machine = sys.argv[2]
    target = sys.argv[3]
    if target[0] != '/':
        raise Error, 'target must be absolute'
    if target[-1] == '/' and len(target) > 1:
        target = target[:-1]
    print "installing %s to %s" % (machine, target)
    installer.install(machine, target)
else:
    raise Error, 'unsupported command'

sys.stdout.write('all done.\n')


