#!/usr/bin/env python
import os, sys
from os.path import join
from optparse import OptionParser

from useless.base import Error, debug
from useless.base.config import Configuration
from useless.db.midlevel import StatementCursor
from useless.sqlgen.clause import Eq, In

from paella.installer.base import InstallerConnection
from paella.installer.util.misc import get_mac_addresses

parser = OptionParser()
opts, args = parser.parse_args(sys.argv[1:])

if not len(args):
    print "We need a machine name as an argument"
    sys.exit(1)



machine = args[0]
macs = get_mac_addresses()

data = dict(hostname=machine)

conn = InstallerConnection()
    
cursor = StatementCursor(conn)
cursor.set_table('current_environment')
for mac in macs:
    data['name'] = mac
    data['value'] = machine
    print 'inserting %s for %s' % (mac, machine)
    cursor.insert(data=data)

print 'config looks like:\n\n'
mcfg = Configuration()
rows = cursor.select(clause=In('name', macs))
for row in rows:
    section = 'machines'
    if not mcfg.has_section(section):
        mcfg.add_section(section)
    mcfg.set(section, row.name, row.value)

    
mcfg.write(sys.stdout)
