#!/usr/bin/env python
import sys
from qt import QApplication
from qt import SIGNAL, SLOT, Qt
from kdecore import KApplication, KCmdLineArgs, KAboutData
from kdecore import KIconLoader
from kdeui import KSystemTray, KMainWindow


from paella.kde.main import PaellaMainApplication
from paella.kde.main import PaellaMainWindow
        
if __name__ == '__main__':
    aboutData = KAboutData('', '', '0.0',
                           'Paella Configuration Management Database', 0,
                           'Joseph Rawson')
    KCmdLineArgs.init(sys.argv, aboutData)

    # setup application instance
    app = PaellaMainApplication()
    app.connect(app, SIGNAL('lastWindowClosed()'), app.quit)

    # register with dcop
    dcop = app.dcopClient()
    appid = dcop.registerAs('paella')

    # create main window
    win = PaellaMainWindow()
    win.show()

    #cfg = app.config()
    #print cfg
    #from kdecore import KLockFile
    #f = KLockFile('foolock')

    # start application loop
    app.exec_loop()
    
