#!/usr/bin/env python
import os, sys
from os.path import join
from optparse import OptionParser

from useless.base import Error, debug
from useless.base.util import makepaths
from useless.db.midlevel import StatementCursor

from paella.base import PaellaConfig
from paella.db.base import get_suite

from paella.installer.base import InstallerConnection
from paella.installer.profile import install_packages_uml
from paella.installer.profile import get_profile_packages

from paella.installer.chroot import ChrootInstaller

parser = OptionParser()

parser.usage = '%prog [options] profile target'
parser.add_option('--logfile', action='store', type='string', dest='logfile',
                  default='/tmp/paella-chroot-installer.log')

opts, args = parser.parse_args(sys.argv[1:])

if os.getuid():
    raise Error, 'need to be root'

cfg = PaellaConfig()
conn = InstallerConnection(cfg)
s = StatementCursor(conn)

profile = args[0]
target = args[1]

target = os.path.abspath(target)

print "installing %s to %s" % (profile, target)
i = ChrootInstaller(conn, logfile=opts.logfile)
i.install(profile, target)





sys.stdout.write('all done.\n')


