#!/usr/bin/python2.3
import os, sys

from paella.db import PaellaConnection
from paella.db.profile.xmlgen import PaellaProfiles

conn = PaellaConnection()
args = sys.argv[1:]
profile = args[0]


profiles = PaellaProfiles(conn)
tfile = file(profile + '.xml', 'w')
xml = profiles.export_profile(profile)
xml.writexml(tfile, indent='\t', newl='\n', addindent='\t')
tfile.close()
