#!/usr/bin/env python
import os, sys
from os.path import join
from optparse import OptionParser

from useless.base import Error, debug

from paella.base import PaellaConfig
from paella.db import PaellaConnection

from paella.admin.management import Manager, SuiteManager
from gtk import mainloop, mainquit

cfg = PaellaConfig('database')
dbname = cfg['dbname']
cfg.change('management_gui')

m = Manager()
if cfg.has_key('manager_size'):
    w, h = map(int, cfg.get_list('manager_size'))
    m.set_size_request(w, h)
if cfg.has_key('manager_pos'):
    x, y = map(int, cfg.get_list('manager_pos'))
    m.set_uposition(x, y)
m.dbconnect(dbname)
m.connect('destroy', mainquit)

for suite in cfg.get_list('management_suites'):
    sm = SuiteManager(m.conn, suite)
    if cfg.has_key('%s_pos' % suite):
        x, y = map(int, cfg.get_list('%s_pos' % suite))
        sm.set_uposition(x, y)

mainloop()
