#!/usr/bin/env python
import sys
from qt import SIGNAL, SLOT

from kdecore import KCmdLineArgs

from useless.kdebase.error import excepthook

from paella.kde.umlmanager.about import AboutData
from paella.kde.umlmanager.main import UmlManagerApplication
from paella.kde.umlmanager.main import UmlManagerMainWindow


if __name__ == '__main__':
    aboutData = AboutData()
    KCmdLineArgs.init(sys.argv, aboutData)

    # setup error handling
    sys.excepthook = excepthook
    
    # setup application instance
    app = UmlManagerApplication()
    app.connect(app, SIGNAL('lastWindowClosed()'), app.quit)

    # register with dcop
    dcop = app.dcopClient()
    appid = dcop.registerAs('paella-kde-umlmanager')

    
    # create main window
    win = UmlManagerMainWindow()
    win.show()

    # set main window in application
    app.setMainWidget(win)

    # start application loop
    app.exec_loop()
    
