#!/usr/bin/python2.3
import os, sys
from xml.dom.minidom import parse

from useless.base import Error

from paella.db import PaellaConnection
from paella.db.profile.xmlgen import PaellaProfiles
from paella.db.profile.xmlparse import ProfileParser


conn = PaellaConnection()
args = sys.argv[1:]
path = args[0]



xml = parse(file(path))
elements = xml.getElementsByTagName('profile')
if len(elements) != 1:
    raise Error, 'bad profile number %s' % len(elements)
element = elements[0]
parsed = ProfileParser(element)
profiles = PaellaProfiles(conn)
profiles.insert_profile(parsed)

