#!/usr/bin/env python
import os, sys

from paella.db import PaellaConnection
from paella.db.trait import Trait

conn = PaellaConnection()
args = sys.argv[1:]
suite = args[0]
trait = args[1]

traitdb = Trait(conn, suite)
traitdb.set_trait(trait)
traitdb.backup_trait('.')
