#!/usr/bin/env python
import os, sys
from optparse import OptionParser

from useless.db.midlevel import StatementCursor

from paella.base import PaellaConfig
from paella.db import PaellaConnection


cfg = PaellaConfig()

parser = OptionParser()

parser.usage = '%prog [options] suite'
parser.add_option('-v', '--verbose', action='store_true', default=False,
                  help="tell me what's happening")
parser.add_option('-u', '--username', dest='user',
                  help="database user", default=cfg.get('database', 'dbusername'))
parser.add_option('--host', dest='host', default=cfg.get('database', 'dbhost'),
                  help='database host')
parser.add_option('-d', '--database', dest='db', default=cfg.get('database', 'dbname'),
                  help="database name")
parser.add_option('-p', '--password', '--passwd', dest='passwd',
                  help='password for database user', default=cfg.get('database', 'dbpassword'))

opts, args = parser.parse_args(sys.argv[1:])

dsn = dict(dbhost=opts.host, dbname=opts.db, dbusername=opts.user,
           dbpassword=opts.passwd)


if not len(args):
    raise RuntimeError, "you need to pass the suite as the first argument"


conn = PaellaConnection(dsn=dsn)
suite = args[0]

cursor = StatementCursor(conn)

table = '%s_trait_package' % suite

package_list = []
for row in cursor.select(table=table):
    package_list.append(row.package)

for package in package_list:
    sys.stdout.write('%s\t\t\t\t\tinstall\n' % package)
    



