#!/bin/bash
mount -t proc /proc proc
echo "deb http://paella/debian questron main contrib non-free" > /etc/apt/sources.list
echo "deb http://developer.linuxtag.net/knoppix ./" >> /etc/apt/sources.list
apt-get -y update
apt-get -y install hwdata-knoppix
apt-get -y install kudzu-knoppix
apt-get -y install cloop-module
apt-get -y install cloop-utils
#apt-get -y install kernel-image-2.4.22-xfs
apt-get -y install hwsetup 
apt-get -y install kudzu-knoppix-dev 
apt-get -y install kudzu-knoppix-vesa
apt-get -y install mkdesktophdicons-knoppix 
apt-get -y install hotplug-knoppix 
apt-get -y install knoppix-remountrw
apt-get -y install scanpartitions-knoppix 
apt-get -y install rebuildfstab-knoppix 
apt-get -y install saveconfig-knoppix
apt-get -y install netcardconfig-knoppix 
apt-get -y install networkconfig-knoppix 
apt-get -y install mkdosswapfile-knoppix
apt-get -y install usleep-knoppix 
apt-get -y install ppp-scripts-knoppix 
apt-get -y install user-profile-knoppix
apt-get -y install mkpersistenthome-knoppix 
apt-get -y install testdisk 
apt-get -y install sshstart-knoppix 
apt-get -y install soundcardconfig-knoppix
apt-get -y install rootshell-knoppix 
apt-get -y install sudoers-knoppix 
apt-get -y install syslinux-knoppix 
apt-get -y install knoppix-customize 
apt-get -y install sitar
apt-get -y install sysvinit-2.84-166 
apt-get -y install genliloconf 
apt-get -y install knoppix-hdinstall 
apt-get -y install ddcxinfo 
apt-get -y install kbdconfig
apt-get -y install etcskel-knoppix 
apt-get -y install netpipes 
apt-get -y install ash-knoppix 
apt-get -y install automount-knoppix 
apt-get -y install checkmem

umount /proc
