Document: paella-client
Title: Debian paella-client Manual
Author: <insert document author here>
Abstract: This manual describes what paella-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/paella-client/paella-client.sgml.gz

Format: postscript
Files: /usr/share/doc/paella-client/paella-client.ps.gz

Format: text
Files: /usr/share/doc/paella-client/paella-client.text.gz

Format: HTML
Index: /usr/share/doc/paella-client/html/index.html
Files: /usr/share/doc/paella-client/html/*.html
