#!/usr/bin/python
import os
from paella.installer.toolkit import InstallerTools

it = InstallerTools()

# here we configure the timezone and localtime
# It's odd that tzdata doesn't respect previously
# made debconf selections, and will remake them
# according to the data that's already present in
# /etc/timezone and /etc/localtime .  Also, if these
# files aren't present, instead of honoring the
# debconf database, it sets the debconf database
# to default values.

# The code below shouldn't have to be performed,
# except to maybe remove the timezone and/or localtime
# files.  After that we're doing the same thing that the
# postinst script does.
timezone_filename = it.target / 'etc/timezone'
localtime_filename = it.target / 'etc/localtime'
if timezone_filename.isfile():
    print "removing /etc/timezone"
    os.remove(timezone_filename)
else:
    print "/etc/timezone wasn't there, skipping."

if localtime_filename.isfile():
    print "removing /etc/localtime"
    os.remove(localtime_filename)
else:
    print "/etc/localtime wasn't there, skipping."

area = it.get('global:tzdata_area')
zone = it.get('global:tzdata_zone')

print "tzdata area and zone are", area, zone

print "writing /etc/timezone"
timezone_filename.write_bytes('%s/%s\n' % (area, zone))

zoneinfo_filename = it.target / 'usr/share/zoneinfo' / area / zone
zoneinfo = file(zoneinfo_filename).read()
print "writing /etc/localtime"
localtime_filename.write_bytes(zoneinfo)
