#!/usr/bin/python
import sys
from paella.installer.toolkit import InstallerTools

it = InstallerTools()
    

cmd = ['aptitude', '-q', '--without-recommends',
       '-o','APT::Install-Recommends=no', '-y', 'install',
       '~pstandard', '~prequired', '~pimportant']

if it.get('base:install_standard') in ["True", "true", 'yes', "Yes"]:
    print "Installing standard packages with command: %s" % ' '.join(cmd)
    # make sure the print statement above goes into the log before
    # the output of the install command
    sys.stdout.flush()
    it.chroot(cmd)
    print "Standard packages installed"
    sys.stdout.flush()
