#!/usr/bin/env python
import os, sys
from os.path import join, isdir

print "configuring bard"
freespace = '/freespace'
dirs = ['bkups', 'nfsroot', 'repos', 'share', 'debian']

for adir in dirs:
    fdir = join(freespace, adir)
    if not isdir(fdir):
        print 'making', fdir
mdir = '/mirrors/debian'
fdir = join(freespace, 'debian')
if isdir(mdir):
    print 'removing', mdir
    os.system('rmdir %s' % mdir)
    print 'linking from', freespace
    os.system('ln -s %s %s' % (fdir, mdir))
print 'making webserver link'
os.system('ln -s %s /var/www/apache2-default/debian' % fdir)
print 'adding umeboshi to cdrom'

add2cdrom = 'adduser umeboshi cdrom'
rmdhcp = 'update-rc.d -f dhcp3-server remove'
stopdhcp = 'update-rc.d -n dhcp3-server stop 10 0 1 2 3 4 5 6 .'
empty_apache_mods = 'rm /etc/apache2/mods-enabled/*'

commands = [
    add2cdrom,
    rmdhcp,
    stopdhcp,
    empty_apache_mods
    ]

map(os.system, commands)

os.chdir('/dev')
os.symlink('scd0', 'cdrom')
os.system('chgrp -R input input/')
os.chdir('/')


#os.system('su postgres createuser -d -A umeboshi')
#os.system('su postgres createuser -D -A paella')
