#!/bin/bash
set -e


echo "Backup live-build cache............."


livebuild=/var/cache/netboot/livebuild

if ! [ -d $livebuild ]; then
    echo "No such directory $livebuild"
    exit 1
fi

if ! [ -d /vagrant/cache ]; then
    echo "Creating /vagrant/cache"
    mkdir /vagrant/cache
fi

pushd $livebuild/cache
for stage in binary bootstrap chroot; do
    directory=packages.$stage
    if [ -d $directory ]; then
	echo "Syncing $directory"
	rsync -aHX packages.$stage /vagrant/cache/
    fi
done

if ! [ -f /vagrant/cache-bootstrap.tar.gz ]; then
    if [ -d bootstrap ]; then 
	echo "Tarring bootstrap"
	sudo tar c bootstrap | gzip > /vagrant/cache-bootstrap.tar.gz
    fi
fi
popd


