#!/bin/bash
set -e

sudo /etc/init.d/apache2 stop

dropdb -U dbadmin paella || true

createdb -U dbadmin paella

sudo /etc/init.d/apache2 start

. ${pillar['paella_virtualenv_basedir']}/venv/bin/activate
initialize_paella_db /srv/src/paella/development.ini


