#!/bin/sh

## live-build(7) - System Build Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

# Including common functions
[ -e "${LIVE_BUILD}/scripts/build.sh" ] && . "${LIVE_BUILD}/scripts/build.sh" || . /usr/lib/live/build.sh

# Setting static variables
DESCRIPTION="$(Echo 'bootstrap non-Debian archive-signing-keys')"
HELP=""
USAGE="${PROGRAM} [--force]"

Arguments "${@}"

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

if [ -n "${_KEY}" ]; then
    Echo_message "Downloading archive-key ${_KEY}..."
    wget -O chroot/key.asc "${_KEY}"
    Echo_message "Importing archive-key ${_KEY}..."
    Chroot chroot "apt-key add key.asc"
    rm -f chroot/key.asc
else
    Echo_message "Skipping archive-keys"
fi

Chroot chroot "apt-get update"

# Creating stage file
Create_stagefile .build/bootstrap_archive-keys
