#!/usr/bin/python
import os
from paella.base.util import makepaths
from paella.installer.toolkit import InstallerTools

it = InstallerTools()
it.set_trait('diskless_server')

bpath = it.get('fileserver_base_path')
lcidr = it.get('global_local_network_cidr')
print bpath
print 'in diskless_server'
print 'environ'
print os.environ
rpath = it.get('diskless_server_diskless_roots_path')
install = it.get('diskless_server_install_diskless')
dprofile = it.get('diskless_server_diskless_profile')
while rpath[0] == '/':
    rpath = rpath[1:]
makepaths(os.path.join(it.target, rpath))
dpath = os.path.join(it.target, rpath, dprofile)
makepaths(dpath)
if install == 'true':
    os.system('paella-chroot-install %s %s' % (dprofile, dpath))
