#!/usr/bin/python
import os
from paella.base import Error
from paella.base.util import makepaths, str2list
from paella.installer.toolkit import InstallerTools

it = InstallerTools()
it.set_trait('diskless_server')

bpath = it.get('fileserver_base_path')
lcidr = it.get('global_local_network_cidr')
print bpath
print 'in diskless_server post'
print 'environ'
print os.environ
rpath = it.get('diskless_server_diskless_roots_path')
install = it.get('diskless_server_install_diskless')
home = it.get('base_homepath')
dprofile = it.get('diskless_server_diskless_profile')
dpath = os.path.join(rpath, dprofile)

exports = file(os.path.join(it.target, 'etc/exports'), 'a+')
exports.write('\n#diskless hosts\n')
exports.write('%s\t%s(rw,async)\n' %  (home, lcidr))
exports.write('%s\t%s(ro,no_root_squash,async)\n' % (dpath, lcidr))
if install == 'true':
    hosts = str2list(it.get('localnet_static_hosts'))
    ips = str2list(it.get('localnet_static_ips'))
    if len(hosts) != len(ips):
        raise Error, 'hosts != ips'
    for i in range(len(hosts)):
        ip, hostname = ips[i], hosts[i]
        opts = 'host=%s mailname=%s' % (hostname, hostname)
        cmd = '/usr/sbin/diskless-newhost %s %s %s' % (dpath, ip, opts)
        print cmd
        chroot_cmd = 'chroot %s %s' % (it.target, cmd)
        print chroot_cmd
        os.system(chroot_cmd)
        line = '%s/%s\t%s(rw,no_root_squash,async)\n' % (rpath, ip, ip)
        exports.write(line)
    exports.write('\n')

exports.close()

    
