interface Repos {
  void parse_release();
  void parse_section(in string section);
  void parse();
  string check_section(in string section);
  Repos this(out Repos this);
  void init(in string source);
  string check_package(in string package, in string section);
  string md5sum(in string package, in string section);
  string filename(in string package, in string section);
  void update();
};

