#!/usr/bin/python
import os
from paella.base.util import makepaths, str2list
from paella.installer.util import setup_modules
from paella.installer.toolkit import InstallerTools

# this is the way to stick modules that you would
# mainly want on a desktop machine in the system - like hid, joydev, etc...

it = InstallerTools()
it.set_trait('desktop')
modules = str2list(it.get('desktop_kmods'))
print modules
setup_modules(it.target, modules)
