#!/usr/bin/python
import os
from paella.base.util import makepaths, str2list
from paella.installer.util import setup_modules
from paella.installer.toolkit import InstallerTools

it = InstallerTools()
it.set_trait('desktop')
modules = str2list(it.get('desktop_kmods'))
print modules
setup_modules(it.target, modules)
