#!/usr/bin/env python
import os, sys
from useless.base.path import path
from useless.base.util import makepaths
from paella.installer.toolkit import InstallerTools

it = InstallerTools()
it.set_trait('uml_head')

cursor = it.conn.cursor(statement=True)
suite = it.suite
traits = it.tr.get_trait_list()
# need to make a method for this
packages = it.tr._packages.packages(traits)
packages = [p.package for p in packages]


all_trait_packages = it.target / 'root/all_trait_packages'
all_trait_packages.write_text(' '.join(packages))
