#!/usr/bin/python
import sys

from useless.base.path import path

from paella.installer.toolkit import InstallerTools

def configure_xorg():
    xorg_output = []
    xorg_filename = it.target / 'etc/X11/xorg.conf'
    if not xorg_filename.isfile():
        print "there's no xorg.conf, skipping configure"
        return
    print "Adding default display mode to", xorg_filename
    for line in file(xorg_filename):
        xorg_output.append(line)
        if 'Monitor\t\t"Configured Monitor"' in line:
            xline = '\tSubSection\t"Display"\n'
            xorg_output.append(xline)
            xline = '\t\tModes\t"1024x768"\n'
            xorg_output.append(xline)
            xline = '\tEndSubSection\n'
            xorg_output.append(xline)
    xorg_filename.write_bytes(''.join(xorg_output))
    

print "post script for vboxbase machine"
it = InstallerTools()
env = it.env()

print "target directory", it.target

print "replacing /etc/apt/sources.list with installer version"
sources_list_filename = it.target / 'etc/apt/sources.list'
sources_list_official_filename = path('%s.official' % sources_list_filename)
sources_list_installer_filename = path('%s.installer' % sources_list_filename)
official = sources_list_filename.bytes()
sources_list_official_filename.write_bytes(official)
sources_list_filename.write_bytes(sources_list_installer_filename.bytes())


xorg_filename = it.target / 'etc/X11/xorg.conf'
if xorg_filename.isfile():
    print "preparing virtualbox packages"
    print "-486 is hardcoded, should use kernel info to pick correct package"
    

    packages = ['virtualbox-ose-guest-modules-2.6.26-1-486',
                'virtualbox-ose-guest-utils']
    print "Installing Packages: %s" % ', '.join(packages)
    sys.stdout.flush()

    it.chroot(['mount', '/proc'])

    cmd = ['apt-get', '-y', 'install'] + packages
    it.chroot(cmd)

    it.chroot(['umount', '/proc'])

    print "we need to find that perl script to modify the xorg.conf for virtualbox"
    it.chroot(['/usr/share/virtualbox/x11config.pl'])
    configure_xorg()
else:
    print "no need for guest modules"
    
