Document: paella-kernels
Title: Debian paella-kernels Manual
Author: <insert document author here>
Abstract: This manual describes what paella-kernels is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/paella-kernels/paella-kernels.sgml.gz

Format: postscript
Files: /usr/share/doc/paella-kernels/paella-kernels.ps.gz

Format: text
Files: /usr/share/doc/paella-kernels/paella-kernels.text.gz

Format: HTML
Index: /usr/share/doc/paella-kernels/html/index.html
Files: /usr/share/doc/paella-kernels/html/*.html

  
