#!/usr/bin/python
import os
from useless.base.util import makepaths
from paella.installer.toolkit import InstallerTools

it = InstallerTools()
it.set_trait('simple_nfsroot')
kernel = it.get('simple_nfsroot_kernel')
print 'installing kernel', kernel
os.system('chroot %s apt-get -y install %s' % (it.target, kernel))


