#!/bin/bash
apt-get update
apt-get -y install ccache debhelper debconf python2.3
ln -s /usr/bin/ccache /usr/local/bin/cc
ln -s /usr/bin/ccache /usr/local/bin/gcc
ln -s /usr/bin/ccache /usr/sbin/cc
ln -s /usr/bin/ccache /usr/sbin/gcc
