#!/bin/bash
echo "paella_dbserver script initiated"
#mount proc /proc -t proc
#init 2
/etc/init.d/postgresql start
#sleep 10
su postgres createdb paella
su --command "createuser -D -A umeboshi" postgres
#/etc/init.d/postgresql stop
#umount /proc
