#!/bin/bash
# this script initializes the defalt structure that was created
# in the pre script to the ldap database
# it also sets up ldap-aware chfn and chsh
/etc/init.d/slapd stop
slapadd -v < /root/paella/files/main.ldif
slapindex -v
cp /tmp/example.ldif /root/paella
rm /tmp/example.ldif
update-rc.d slapd defaults
mv /usr/bin/chfn /usr/bin/chfn.orig
mv /usr/bin/chsh /usr/bin/chsh.orig
cp /usr/share/doc/libpam-ldap/examples/chfn /usr/bin
cp /usr/share/doc/libpam-ldap/examples/chsh /usr/bin
chmod +x /usr/bin/chsh /usr/bin/chfn
