#!/bin/bash
# /etc/acpi/lid.sh
# Initiates a suspend when the lid is closed or resume when lid is opened.
# 
#
# Your sleep file
acpi_sleep="/proc/acpi/sleep"
ACPID_AMI_SLEEPING=/var/run/acpid.sleeping
mode="3"
if [ "$0" = "sleep.sh" ]; then
	mode=4
fi
if [ ! -f $acpi_sleep ]; 
	then logger -p local1.warning -t "acpi lid" "no sleep mode possible"
fi

##############
# going asleep
##############

#
# Remember in /var/run that we are sleeping
#
touch "$ACPID_AMI_SLEEPING"

sync; sync; sync

# we go into standby mode
grep -q $mode $acpi_sleep
ret=$?
if [ $ret -eq 0 ]; then
	echo $mode > $acpi_sleep
	exit 0
fi

logger -p local1.warning -t "acpi lid" "no sleep state defined"
