Document: paella
Title: Debian paella Manual
Author: <insert document author here>
Abstract: This manual describes what paella is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/paella/paella.sgml.gz

Format: postscript
Files: /usr/share/doc/paella/paella.ps.gz

Format: text
Files: /usr/share/doc/paella/paella.text.gz

Format: HTML
Index: /usr/share/doc/paella/html/index.html
Files: /usr/share/doc/paella/html/*.html

  
