#!/bin/bash
set -e

/etc/init.d/salt-minion stop || true

update-rc.d -f salt-minion remove




cat <<EOF > /etc/salt/minion
master: 10.0.4.1
id: debian
EOF



cat <<EOF > /etc/rc.local
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

if ! [ -r /etc/salt/highstate-complete ]; then
    salt-call state.highstate
    touch /etc/salt/highstate-complete
fi
exit 0

EOF
