#!/usr/bin/python
import os

from useless.base.util import makepaths
from paella.installer.toolkit import InstallerTools

it = InstallerTools()

it.set_trait('fileserver')

bpath = it.get('fileserver_base_path')
rpath = bpath
print 'bpath is:', bpath

while bpath[0] == '/':
    bpath = bpath[1:]
bpath = os.path.join(it.target, bpath)
share = it.get('fileserver_share_path')
common = it.get('fileserver_common_path')
admin = it.get('fileserver_admin_path')
office = it.get('fileserver_office_path')
makepaths(bpath)
for p in [share, common, admin, office]:
    fullpath = os.path.join(rpath, p)
    os.system('chroot %s mkdir -p %s' % (it.target, fullpath))
    if p in [share, office]:
        if p == 'share':
            os.system('chroot %s chmod 777 %s' % (it.target, fullpath))
        os.system('chroot %s chgrp office %s' % (it.target, fullpath))
        os.system('chroot %s chmod g+s %s' % (it.target, fullpath))
        os.system('chroot %s chmod g+w %s' % (it.target, fullpath))
        makepaths(os.path.join(it.target, bpath, common, 'to_common'))
    elif p == 'admin':
        os.system('chroot %s chgrp admin %s' % (it.target, fullpath))
        os.system('chroot %s chmod g+w %s' % (it.target, fullpath))
        
if it.get('global_install_opencd') in ['true', 'True', 'yes', 'Yes', 't', 'T', 'y', 'Y']:
    nfshost = it.default.get('installer', 'nfs_common_host')
    export = it.default.get('installer', 'nfs_common_export')
    isopath = it.default.get('installer', 'common_opencdiso')
    isofilename = os.path.basename(isopath)
    mtpt = '/tmp/common'
    makepaths(mtpt)
    iso = os.path.join(mtpt, isopath)
    os.system('mount -o nolock %s:%s %s' % (nfshost, export, mtpt))
    print mtpt, 'mounted'
    print file('/proc/mounts').read()
    isomtpt = '/tmp/isomount'
    cmnpath = os.path.join(bpath, common)
    opencd_path = os.path.join(cmnpath, 'opencd')
    makepaths(isomtpt)
    makepaths(opencd_path)
    print 'iso is at', iso
    os.system('cp %s %s' % (iso, cmnpath))
    copied_iso = os.path.join(cmnpath, isofilename)
    isomntcmd = 'mount -t iso9660 -o loop %s %s' % (copied_iso, isomtpt)
    print isomntcmd
    os.system(isomntcmd)
    print isomtpt, 'mounted'
    print file('/proc/mounts').read()
    cpcmd = 'cp -a %s/* %s' % (isomtpt, opencd_path)
    print 'cpcmd', cpcmd
    os.system(cpcmd)
    os.system('umount %s' % isomtpt)
    print isomtpt, 'unmounted'
    os.system('umount %s' % mtpt)
    print mtpt, 'unmounted'
    print file('/proc/mounts').read()
    os.remove(copied_iso)
else:
    print 'skipping opencd iso installation'
    
