#!/bin/bash
echo "wmaker script initiated"
update-alternatives --install /usr/bin/x-window-manager x-window-manager /usr/bin/icewm 00
update-alternatives --install /usr/bin/x-window-manager x-window-manager /usr/bin/wmaker 99
