#!/bin/bash
echo "base script initiated"
apt-get -y update
#dselect update
echo "doing upgrade"
#dselect install
apt-get -y upgrade

/etc/init.d/mdadm stop
killall -9 mdadm
env DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -plow locales
exit 0
