#!/bin/bash
echo "simple_nfsroot script initiated"
touch fastboot
chmod 0 fastboot
#update-rc.d -f checkroot.sh remove
#update-rc.d -f checkfs.sh remove
#update-rc.d -f networking remove
#update-rc.d remount_rootnfs.sh start 01 S .


