#!/bin/bash
echo "paella_devel script initiated"
USER=umeboshi
HOME=/home/$USER
WORKSPACE=$HOME/workspace

apt-get -y update
apt-get -y install paella-installer paella-paelladb paella-admin
#mkdir $WORKSPACE
#mkdir -p $HOME/bin
#chown -R $USER:$USER $HOME
#adduser $USER uml-net
