#!/usr/bin/python
import sys

from useless.base.path import path

from paella.base.template import TemplatedEnvironment

from paella.installer.toolkit import InstallerTools

print "config script for final trait"
#it = InstallerTools()
print "we need to update the home directories for the users created"
print "in the users trait."
